inp1 = input("Enter the name of the employee ")
inp2 = int(input("Enter the age of the employee "))
inp3 = float(input("Enter the weight of the employee"))
inp4 = bool(input("Does the employee own a vehicle"))
print(inp1)
print(inp2)
print(inp3)
print(inp4)